### ISSUE TITLE
mask=False in wav2vec_2.py 

### ISSUE THREAD

**Issue by XuLw** [phecda-xu/wav2vec-project#1]
请教一下！ 为什么wav2vec在推理的时候要将mask 设置为 False， 没找到相关说明，并且两种版本都有，如能告知感激不尽！

`f = model.final_proj(p)
print("f.size:", f.size())

c = model(wav_input_16khz, **mask=False,** features_only=True)["x"]
print('c size:', c.size())`

**Comment by phecda-xu** [comment]
> 请教一下！ 为什么wav2vec在推理的时候要将mask 设置为 False， 没找到相关说明，并且两种版本都有，如能告知感激不尽！
> 
> `f = model.final_proj(p)
> print("f.size:", f.size())
> 
> c = model(wav_input_16khz, **mask=False,** features_only=True)["x"]
> print('c size:', c.size())`

看论文里面，`To pre-train the model we mask a certain proportion of time steps in the latent feature encoder space
(§ 3.1), similar to masked language modeling in BERT [9].`

mask只是训练时候对输入数据进行处理的一种策略，使用mask可以更好的训练自监督学习模型。推理的时候，为保证效果以及输出稳定性，应该给模型全部真实的数据，所以不需要再对输入数据进行mask（如果推理使用mask，你会发现同样的输入数据，每次输出的都会不一样）。可以类比于drop_out层的使用。

**Comment by XuLw** [comment]
> > 请教一下！ 为什么wav2vec在推理的时候要将mask 设置为 False， 没找到相关说明，并且两种版本都有，如能告知感激不尽！
> > `f = model.final_proj(p)
> > print("f.size:", f.size())
> > c = model(wav_input_16khz, **mask=False,** features_only=True)["x"]
> > print('c size:', c.size())`
> 
> 看论文里面，`To pre-train the model we mask a certain proportion of time steps in the latent feature encoder space (§ 3.1), similar to masked language modeling in BERT [9].`
> 
> mask只是训练时候对输入数据进行处理的一种策略，使用mask可以更好的训练自监督学习模型。推理的时候，为保证效果以及输出稳定性，应该给模型全部真实的数据，所以不需要再对输入数据进行mask（如果推理使用mask，你会发现同样的输入数据，每次输出的都会不一样）。可以类比于drop_out层的使用。

感谢你的回复！你说的我了解了，可以再问一个问题吗？就是说，测试的时候我也发现了如果继续使用mask，结果确实是不稳定的，所以才找原因，找到了mask这里，想问的是： 如果推理测试的时候还使用mask的话，那这个测试精度结果还有效吗？因为我发现关掉mask进行测试精度掉的有点厉害。谢谢~

**Comment by phecda-xu** [comment]
> > > 请教一下！ 为什么wav2vec在推理的时候要将mask 设置为 False， 没找到相关说明，并且两种版本都有，如能告知感激不尽！
> > > `f = model.final_proj(p) print("f.size:", f.size()) c = model(wav_input_16khz, **mask=False,** features_only=True)["x"] print('c size:', c.size())`
> > 
> > 
> > 看论文里面，`To pre-train the model we mask a certain proportion of time steps in the latent feature encoder space (§ 3.1), similar to masked language modeling in BERT [9].`
> > mask只是训练时候对输入数据进行处理的一种策略，使用mask可以更好的训练自监督学习模型。推理的时候，为保证效果以及输出稳定性，应该给模型全部真实的数据，所以不需要再对输入数据进行mask（如果推理使用mask，你会发现同样的输入数据，每次输出的都会不一样）。可以类比于drop_out层的使用。
> 
> 感谢你的回复！你说的我了解了，可以再问一个问题吗？就是说，测试的时候我也发现了如果继续使用mask，结果确实是不稳定的，所以才找原因，找到了mask这里，想问的是： 如果推理测试的时候还使用mask的话，那这个测试精度结果还有效吗？因为我发现关掉mask进行测试精度掉的有点厉害。谢谢~

1、我的理解：单就wav2vec模型本身而言，使用mask和不使用mask，不影响模型对语音数据的表达，也就是说生成的vector都是有效的（但是不等价）；加mask无非增加了些计算量。

2、不清楚你是怎么测的啊，你这个测试精度是指什么？我没在论文里看到有对模型的直接测试，只有结合ASR模型的测试，这种测试需要结合wav2vec模型进行训练，wav2vec在这里是作为特征提取器的角色，输出特征矩阵。

      你如果在训练ASR的时候将mask设置为True，那么测试的时候就不要改；
      
      如果说，你将mask设为False导致精度下降很多，那可能就是你在用的时候没有保持一致，可以检查一下。
